*Get data from local csv file;
PROC IMPORT OUT= WORK.ohiocrime
			DATAFILE='/folders/myfolders/sasuser.v94/hw5/ohiocrimehm.xls'
			dbms=XLS REPLACE;
	GETNAMES= YES;
	DATAROW=2;
run;

*RENAME VARIABLES;
DATA ohiocrime; SET ohiocrime;
*DEPENDENT VARIABLES;
RENAME 	V10=SUMMERJOBS
		V12=RECPROGRAMS
		V16=TMTPROGRAMS
		V23=FAMSUPPORT;
*INDEPEN VARS (CONTINUOUS);
RENAME 	V64=SINNERSENTIMENT
		V67=RELIGIOUS
		v86=POLITICS
		V87=INCOME;
*INDEPEN VARS (CATEGORICAL);
RENAME 	V70=GENDER
		V71=RACE
		V72=EDUCATION;
*COULD BE CATEGORICAL OR CONTINUOUS;
RENAME V73=BROKENINTO;
RUN;

*Delete rows with missing data; 
DATA ohiocrime; SET ohiocrime;
if nmiss(of _numeric_) > 0 then delete;
run;


PROC SORT DATA=ohiocrime; BY RACE EDUCATION;
 PROC MEANS DATA=ohiocrime;
VAR SUMMERJOBS;
 BY RACE EDUCATION;
 OUTPUT OUT=dataMEAN;
  RUN;
  
DATA DATAMEAN; SET DATAMEAN; IF _STAT_='MEAN';
RUN;

PROC PLOT DATA=datamean;
	PLOT SUMMERJOBS*EDUCATION=RACE;
RUN;

proc glm data=ohiocrime;
class RACE EDUCATION;
model SUMMERJOBS=RACE EDUCATION RACE*EDUCATION / solution;
manova h=RACE EDUCATION RACE*EDUCATION;
OUTPUT OUT=OUTSTAT RESIDUAL=RESIDUALA RESIDUALB;
run;  

PROC SORT DATA=ohiocrime; BY RACE ; RUN;

DATA ohiocrime; SET ohiocrime;
  LENGTH TRTCOMB $20;
  IF RACE=1 AND EDUCATION=1 THEN TRTCOMB="black1";
  IF RACE=1 AND EDUCATION=2 THEN TRTCOMB="black2";
  IF RACE=1 AND EDUCATION=3 THEN TRTCOMB="black3";
  IF RACE=1 AND EDUCATION=4 THEN TRTCOMB="black4";
  IF RACE=1 AND EDUCATION=5 THEN TRTCOMB="black5";
  IF RACE=1 AND EDUCATION=6 THEN TRTCOMB="black6";
  IF RACE=1 AND EDUCATION=7 THEN TRTCOMB="black7";
  IF RACE=1 AND EDUCATION=8 THEN TRTCOMB="black8";
  IF RACE=2 AND EDUCATION=1 THEN TRTCOMB="white1";
  IF RACE=2 AND EDUCATION=2 THEN TRTCOMB="white2";
  IF RACE=2 AND EDUCATION=3 THEN TRTCOMB="white3";
  IF RACE=2 AND EDUCATION=4 THEN TRTCOMB="white4";
  IF RACE=2 AND EDUCATION=5 THEN TRTCOMB="white5";
  IF RACE=2 AND EDUCATION=6 THEN TRTCOMB="white6";
  IF RACE=2 AND EDUCATION=7 THEN TRTCOMB="white7";
  IF RACE=2 AND EDUCATION=8 THEN TRTCOMB="white8";
RUN;

PROC GLM DATA=ohiocrime ORDER=DATA;
 CLASS TRTCOMB;
 MODEL SUMMERJOBS = TRTCOMB / SOLUTION;
 CONTRAST 'High school grad vs non-high school grad' TRTCOMB
     3 3 -1 -1 -1 -1 -1 -1 3 3 -1 -1 -1 -1 -1 -1;
 MANOVA H=TRTCOMB;
RUN;

PROC SGPLOT DATA=ohiocrime;
	hbox SUMMERJOBS / category=INCOME;
RUN;

PROC SGPLOT DATA=ohiocrime;
	hbox SUMMERJOBS / category=POLITICS;
RUN;

PROC GLM DATA=ohiocrime;
	CLASS RACE EDUCATION;
	MODEL SUMMERJOBS FAMSUPPORT = RACE EDUCATION POLITICS / SOLUTION;
	MANOVA H= RACE EDUCATION POLITICS / mstat=exact;
	OUTPUT OUT=OUTSTAT RESIDUAL=RESIDUALA RESIDUALB;
RUN;

*check multivariate normality of the residuals;
*INCLUDE THE MACRO;
filename foo2 url "http://reuningscherer.net/stat660/sas/multnorm.sas.txt";
%include foo2;

%multnorm(data=OUTSTAT, var= RESIDUALA RESIDUALB);
run;






