---
title: "SDS 363 - Final Project"
author: "Neehaar Gandhi, David Liu, Josh Brooks"
date: "4/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Introduction
This project analyzes the data that drives the 2018 edition of the officially licensed Fédération Internationale de Football Association (International Federation of Association Football) video game, titled FIFA 18, produced by Electronic Arts (EA). Association football (soccer) is by far the most popular sport in the world, so it should come as no surprise that the game has became something of a cultural icon. To date, the FIFA franchise is the sixth-best selling video game series in history, with its popularity likely to continue rising. A new version of the game is released once per year, making the 2018 edition of the game the twenty-fifth installment. 
Within the electronic entertainment industry, sports video games present a unique, data-driven challenge. Like the creators of any other game type, sports game engineers want to manufacture a comprehensive representation of reality; they want their manufactured world to be satisfactorily engrossing for players. At the same time, unlike other sorts of games, sports games must try accurately represent a reality that is constantly scrutinized to an almost shocking degree. Gamers want to be titillated and drawn in, while rapid sports fans simply will never tolerate misrepresentation of their favorite players.
This tension -- between manufacturing a maximally effective fictitious world and satisfying players’ wish to play with real people -- leads to a wealth of data-driven challenges. This is the central consideration that underscores our analysis. We will use the game’s player rating data, which is described in detail in a following section, to ask and answer questions about the relationships between soccer player attributes, real, electronic, and somewhere between. 

#Design and Primary Questions
One area of interest for us is understanding better how EA producers ultimately come to their “Overall” player ratings. These overall ratings are not as important to game play as they may initially seem -- given that players are already rated on a number of particular skills -- but it is suspected that changes in overall rating affect an in-game player’s likelihood of successfully carrying out a task. In addition, and probably more importantly, overall ratings are important because they great affect the way that gamers interact with the game. To establish hierarchies of gamer skill, gamers must be able to assess quickly whether two teams or two players are of equivalent quality. Further, it is well-known that overall ratings are often much higher than the average of their parts. Players with medium-level skills may often have higher overall ratings based on what they offer the team on top of their rated qualities and skills. Thus, a principal question for us is: What sets of variables correspond with higher overall scores, and can we use those variables to tell a story about what an ‘x-factor’ might be? To answer this we will use factor analysis. In so doing we hope we will be able to find a latent factor that might tell a story about what makes players valuable on the field. 
Related to our previous question about underlying factors, we also see examination of this dataset as a good opportunity to look for patterns of players within particular position groups. Players of different sizes and physical gifts can be successful at the same positions, they simply must play somewhat differently. Lionel Messi, for example, is without equal in dribbling and finishing, but cannot play particularly physically, due to his small size. When he plays center forward, we might think of him as playing a sub-position of forward often called ‘false nine’. Without getting too bogged down in tactics, this means that he does not push forward when his team possesses the ball, but rather sits back and looks for opportunities to pass through to his teammates, or to receive the ball and dribble through the defense. Within broad positional categories -- back, midfielder, forward -- can we see discernable subgroups of players? Again, we would certainly expect to see this, given subjective understandings of soccer tactics. Using k-means as a clustering technique, we hope to create a readable picture of positional subgroups. 
Finally, we want to look at the interactions between FIFA players’ nationalities and their skills in various areas. In the international soccer community, it is very common to talk about geographic regions as very different. For instance, it has become accepted wisdom to say that Latin American teams play a more skillful, less team-oriented style, while European teams play with more precision and less individual skill. We hope to see whether the data bear this out. In this vein, our third question for analysis will be: Do different country groups create players that are differently abled in particular facets of the game? To test this we will use MANOVA and attempt to establish differences in ability means between various nationality groups.

#Data
The dataset is quite large, as a result of the game’s intention of accurately representing every male professional soccer player in the world. While the video game surely requires an even larger ocean of data to operate, we will concern ourselves only with the player rating data -- those data that describe the qualities of individual athletes and their particular traits and skills. 
There are a few broad categories of data in the set. The first type of variable is made up of the information that describes a player and his location. These include physical traits like height and weight, as well as the club for which the player plays professionally, the country for which the player plays in international competition, the player’s wage per game-week, and the like. All of this information is taken directly from publicly available postings by the players’ clubs. Wage is rounded to the nearest thousand, which could change the data somewhat at lower numbers. 
The second, and ultimately the most significant, type of variable in the set comprises ratings for various in-game skills and actions on a 100 point scale. The full list has more than thirty predictors, which will be detailed below. Among them are skilled related to playing offense, playing defense, passing, athleticism, and everyone else that one must do on a soccer field. Some examples are: “Ball Control” (ability to keep possession of the ball and place it in a favorable position for future actions), “Finishing” (generalized fast-twitch ability to accurately kick the ball into the goal after receiving a pass), “Marking” (ability to successfully keep with a player while playing defense, and prevent him from receiving the ball), and “Agility” (a general measure of ability to move quickly over short distances and control one’s body through space). 
These skill ratings are, of course, highly subjective. They do not appear out of thin air; they must be created and compiled by human raters. EA are upfront about their process. They delegate the much of the task of watching and evaluating to a network of over 9000 “data reviewers”, made up of professionals (coaches) and amateurs (qualified fans). The material from the reviewers comes to a group of a few-hundred editors, who compile the data into the rating categories listed below. With this in mind, we can think of these ratings as the results of a large survey, in which soccer fanatics are asked to watch a great deal of game film and give answers to questions about player ability. This is not exactly true -- EA’s producers and editors tweak the data as they see fit, and the sampling of data reviewers is surely not perfectly random -- but thinking of it this way provides a general picture.
The third group of predictors is smaller and generally less useful. It is made up of semi-categorical predictors (categorical skill ratings with five levels). These include “Skill Moves” and “International Reputation”. We will largely ignore these in our analysis -- they are less about soccer, and more about game mechanics. Skill moves is a good example of this category. From 1 to 5, as players go to up higher thresholds of skill rating, they gain the ability to carry out particular in-game actions.

[insert variables below]

#Descriptive plots, summary statistics

#Multivariate Analysis and Discussion of Results

#Conclusions and Discussion

#Points for further analysis
